plugins:
  - jekyll-archives
  - jekyll/tagging
  - jekyll-tagging-related_posts
permalink: /:year/:month/:day/:title
paginate: 7
jekyll-archives:
  enabled:
   - tags
   - categories
   - month
   - year
  layouts:
    year: date-archive
    month: date-archive
    category: categories-archive
    tag: categories-archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/:name/'
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - divshot.json
  - _site
  - circle.yml
  - divshot.json
production: true
production_url: https://jonas.brusman.se
title : Jonas Brusman
author:
  name: Jonas Brusman
  email: jonas@brusman.se
  github: himynameisjonas
  twitter: himynameis jonas
sass:
  sass_dir: assets/_sass
